language: c

os: linux
dist: trusty
# Use full depth for SonarCloud
git:
  depth: false 

install:
  - sudo pip install gcovr
  - gem install ceedling

script:
  - build-wrapper-linux-x86-64 --out-dir bw-output make sonar
  - ceedling test:all
  - ceedling gcov:all utils:gcov
  - gcov -b -c build/gcov/out/*.gcno
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

addons:
  sonarcloud:
    organization: "ruuvi"
    projectKey: "ruuvi.endpoints.c"
