
function incbuild()
{
  var file = "buildnum.h";
  var text = "// This file is auto generated by buildnum.js\n\n#define BUILDNUMBER \"Build ";
  var date = new Date();

  // year
  text += date.getFullYear().toString();

  // month
  if(date.getMonth()+1<10) {
    text += "0";
  }
  text += (date.getMonth()+1).toString();

  // day
  if(date.getDate()<10) {
    text += "0";
  }
  text += date.getDate().toString();

  // hour
  if(date.getHours()<10) {
    text += "0";
  }
  text += "_" + date.getHours().toString();

  // minute
  if(date.getMinutes()<10) {
    text += "0";
  }
  text += date.getMinutes().toString();

  // seconds
  if(date.getSeconds()<10) {
    text += "0";
  }
  text += date.getSeconds().toString();

  text += "\"\n";
  CWSys.writeStringToFile(file, text);
}

// Executed when script loaded.
incbuild();
