# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, split-repos, merge_3.31.1 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      working-directory: /github/workspace
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: docker://sysexect/ruuvi-build-env:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: link sdk
        run: ln -s /tools/nRF5_SDK_15.3.0_59ac345 /__w/ruuvi.firmware.c/ruuvi.firmware.c/nRF5_SDK_15.3.0_59ac345

      - name: create new buildnum.h
        run: fish --command="echo '#define BUILDNUMBER \"Build '(date +\"%Y%m%d_%H%M%S\")'\"' && echo '#define BUILDNUMBER \"Build '(date +\"%Y%m%d_%H%M%S\")'\"' > src/buildnum.h"

      - name: build sourcecode
        run: make -j $(nproc --all) build

      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: src/targets/ruuvitag_b/armgcc

